### ISSUE TITLE
Is it possible to customize for new language?

### ISSUE THREAD

**Issue by ican24** [benob/recasepunc#6]
Dear Benoit Favre,

Your project is really important!
Is it possible to customize for new language?
If yes, could you tell short hints for it?

Thank you in advance!

**Comment by benob** [comment]
Start by getting some text corpora, for example from https://data.statmt.org/cc-100/
Then, run preprocessing, for example with
```
python recasepunc.py preprocess --lang $LANG < input.txt > input.case+punc
```
This normalizes the text and generates a file with one token per line, each line having three columns: <token> <case-label> <punct-label>. It should be pretty language independent. You can probably roll your own if the default is not good for your target language. Check the preprocess_text() function for details. One important thing is that you will have to apply the same preprocessing at test time.

Once you have that file, you need to tokenize it with BPE (some words may be split). It's done through
```
python recasepunc.py tensorize input.case+punc input.case+punc.x input.case+punc.y --lang $LANG
```
The lang flag is necessary because some LMs from the transformers library have different encodings for subwords.
In addition, this step also converts the data to tensors and saves them to files for later training. This step should really be separated in two steps. Again, if your LM has yet another way of splitting words in tokens, you would have to modify the function make_tensors().

Finally, training is performed this way:
```
python recasepunc.py train train.x train.y valid.x valid.y checkpoint/path --lang $LANG
```

**Comment by ican24** [comment]
Everything is going ok. Just one small question: How may I generate valid.x and valid.y correctly? 
I am sorry, but I am not familiar with this tokenized format. 
Thank you in advance!

**Comment by benob** [comment]
I forgot to mention that you need to split the text data in two sets: training and validation. This allows selecting the best checkpoint according to F-score. The steps for each set are the same: normalize, generate case and punctuation labels, apply BPE, and make tensors.

**Comment by ican24** [comment]
Thank you very much!
